[project]
name = "log_zipper"
version = "0.1.0"
description = "logrotate but better."
requires-python = ">=3.11"
dependencies = [
    "commonwealth==0.1.0",
    "loguru==0.5.3",
]

[tool.uv.sources]
commonwealth = { workspace = true }
