import colorsys
import textwrap
from typing import Dict, Tuple


def parse_hex(color: str) -> Tuple[float, float, float]:
    rgb_hex_digits = 6
    value = color.lstrip("#")
    if len(value) != rgb_hex_digits:
        raise ValueError(f"Invalid hex color: {color}")
    try:
        r = int(value[0:2], 16) / 255.0
        g = int(value[2:4], 16) / 255.0
        b = int(value[4:6], 16) / 255.0
    except ValueError as exception:
        raise ValueError(f"Invalid hex color: {color}") from exception
    return r, g, b


def to_hex(rgb: Tuple[float, float, float]) -> str:
    r, g, b = (max(0.0, min(1.0, channel)) for channel in rgb)
    return f"#{int(round(r * 255)):02X}{int(round(g * 255)):02X}{int(round(b * 255)):02X}"


def shift_lightness(
    rgb: Tuple[float, float, float], lightness_factor: float, saturation_factor: float
) -> Tuple[float, float, float]:
    """
    Shift HSL lightness/saturation by relative factors.

    `lightness_factor` and `saturation_factor` are multipliers (e.g. 0.75 means 75% of the original).
    Saturation is left untouched on near-grayscale inputs to avoid tinting pure greys.
    """
    r, g, b = rgb
    hue, lightness, saturation = colorsys.rgb_to_hls(r, g, b)
    new_lightness = max(0.0, min(1.0, lightness * lightness_factor))
    # Skip saturation shifting on near-grayscale colors so pure grey stays grey
    new_saturation = saturation if saturation < 0.05 else max(0.0, min(1.0, saturation * saturation_factor))
    return colorsys.hls_to_rgb(hue, new_lightness, new_saturation)


def derive_palette(primary_hex: str) -> Dict[str, str]:
    """
    Derive a 3-anchor BlueOS-style gradient palette from a single primary color.

    Mirrors the relationship between BR_BLUE -> MARINER_BLUE -> BLUE_WHALE:
    progressively darker and slightly more saturated. Uses relative shifts so
    the gradient stays visible across the whole hue spectrum.
    """
    rgb = parse_hex(primary_hex)
    light = rgb
    mid = shift_lightness(rgb, lightness_factor=0.55, saturation_factor=1.18)
    dark = shift_lightness(rgb, lightness_factor=0.20, saturation_factor=1.45)

    # Scrollbar derivatives (Vuetify-style darken steps relative to primary)
    scroll_track = shift_lightness(rgb, lightness_factor=0.65, saturation_factor=1.05)
    scroll_thumb = shift_lightness(rgb, lightness_factor=0.45, saturation_factor=1.15)

    return {
        "light": to_hex(light),
        "mid": to_hex(mid),
        "dark": to_hex(dark),
        "scroll_track": to_hex(scroll_track),
        "scroll_thumb": to_hex(scroll_thumb),
    }


def render_css(primary_hex: str) -> str:
    palette = derive_palette(primary_hex)
    light = palette["light"]
    mid = palette["mid"]
    dark = palette["dark"]
    scroll_track = palette["scroll_track"]
    scroll_thumb = palette["scroll_thumb"]

    # 0x55 ~= 33% alpha, 0x88 ~= 53% alpha — same ratios used in App.vue.
    # Selectors are prefixed with `html` to bump specificity above App.vue's
    # bundled rules: Vite injects App.vue's CSS link AFTER /userdata/styles/
    # in <head>, so equal-specificity rules with !important would otherwise win.

    return textwrap.dedent(
        f"""
        /* Auto-generated by the BlueOS customization service. Do not edit by hand. */
        /* Primary color: {primary_hex} */

        html .light-background {{
          background-color: {light} !important;
          background-image: linear-gradient(160deg, {light} 0%, {mid} 100%) !important;
        }}

        html .dark-background {{
          background-color: {mid} !important;
          background-image: linear-gradient(160deg, {mid} 0%, {dark} 100%) !important;
        }}

        html .light-background-glass {{
          background-color: {light}55 !important;
          background-image: linear-gradient(160deg, {light}88 0%, {mid}88 100%) !important;
          backdrop-filter: blur(4.5px) !important;
          -webkit-backdrop-filter: blur(10px) !important;
        }}

        html .dark-background-glass {{
          background-color: {mid}55 !important;
          background-image: linear-gradient(160deg, {mid}88 0%, {dark}88 100%) !important;
          backdrop-filter: blur(4.5px) !important;
          -webkit-backdrop-filter: blur(10px) !important;
        }}

        html ::-webkit-scrollbar-track {{
          box-shadow: inset 0 0 1px grey;
          background: {scroll_track} !important;
        }}

        html ::-webkit-scrollbar-thumb {{
          background: {scroll_thumb} !important;
          transition: visibility 2s;
        }}

        html ::-webkit-scrollbar-thumb:hover {{
          background: {light} !important;
        }}
    """
    ).strip()
