[project]
name = "cable_guy"
version = "0.1.0"
description = "A simple web api to provide access to ethernet configuration."
requires-python = ">=3.11"
dependencies = [
    "commonwealth==0.1.0",
    "fastapi==0.125.0",
    "fastapi-versioning==0.10.0",
    "loguru==0.7.3",
    "psutil==7.1.3",
    "pydantic==2.12.5",
    "pyroute2==0.8.1",
    "sdbus-networkmanager==2.0.0",
    "uvicorn==0.38.0",
]

[tool.uv]
package = false
