#!/usr/bin/env bash

COMPANION_PATH=/home/pi
SERVICES_PATH=$COMPANION_PATH/services

SERVICES=(
    'cable_guy',"$SERVICES_PATH/cable_guy/main.py"
    'wifi',"$SERVICES_PATH/wifi/main.py"
    'autopilot',"$SERVICES_PATH/ardupilot_manager/main.py"
    'helper',"$SERVICES_PATH/helper/main.py"
    'video',"mavlink-camera-manager --verbose"
)

tmux start-server
function create_service {
    tmux new -d -s "$1" || true
    tmux send-keys -t "$1:0" "$2" C-m
}

echo "Starting services.."
for TUPLE in "${SERVICES[@]}"; do
    IFS=',' read NAME EXECUTABLE <<< ${TUPLE}
    echo "Service: $NAME: $EXECUTABLE"
    create_service $NAME "$EXECUTABLE"
done

echo "Companion running!"