[project]
name = "ardupilot_manager"
version = "0.0.1"
description = "AutoPilot service manager."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiocache==0.12.3",
    "appdirs==1.4.4",
    "commonwealth==0.1.0",
    "fastapi==0.125.0",
    "fastapi-versioning==0.10.0",
    "loguru==0.7.3",
    "packaging==25.0",
    "psutil==7.1.3",
    "pydantic==2.12.5",
    "pyelftools==0.30",
    "pyserial==3.5",
    # This dependency needs to be locked since it is used by fastapi
    "python-multipart==0.0.21",
    "smbus2==0.6.1",
    "uvicorn==0.38.0",
    "validators==0.35.0",
]

[tool.uv]
package = false
