#!/bin/sh

set -e

echo "Running pre push hook!"
repository_path=$PWD/$(git rev-parse --git-dir)/..

echo "Running isort.."
isort --check-only "$repository_path"

echo "Running black.."
black --check --line-length=120 "$repository_path"

echo "Running pylint.."
pylint $(git ls-files '*.py')

echo "Running mypy.."
git ls-files '*.py' | xargs --max-lines=1 mypy --ignore-missing-imports --warn-unreachable --allow-untyped-decorators --strict

echo "Running pytest.."
pytest --cov-fail-under=63 --cov="$repository_path"/{bootstrap,core}

exit 0