#!/bin/sh

set -e

# Check if pipenv is installed
command -v pipenv >/dev/null 2>&1 || {
    echo >&2 "pipenv is not installed. Aborting. Please install it and try again."
    exit 1
}

# Check if shellcheck is installed
command -v shellcheck >/dev/null 2>&1 || {
    echo >&2 "shellcheck is not installed. Aborting. Please install it and try again."
    exit 1
}

# Check if parallel is installed
command -v parallel >/dev/null 2>&1 || {
    echo >&2 "parallel is not installed. Aborting. Please install it and try again."
    exit 1
}

pipenv install poetry
pipenv run poetry install
# download some required files if they are not present
echo "installing mavlink-router"
pipenv run ./core/tools/mavlink_router/bootstrap.sh
echo "installing mavp2p"
pipenv run ./core/tools/mavp2p/bootstrap.sh
echo "installing ardupilot_tools"
pipenv run ./core/tools/ardupilot_tools/bootstrap.sh

isort_extra_args="--check-only --diff"
black_extra_args="--check --diff"
fixing="false"

for arg in "$@"; do
  case $arg in
    --fix)
      isort_extra_args=""
      black_extra_args=""
      fixing="true"
      ;;
    *)
      echo "Unknown argument: $arg"
      exit 1
      ;;
  esac
done

echo "Running pre push hook!"
repository_path=$(git rev-parse --show-toplevel)
tag_name=$(git tag --points-at=HEAD | head -n 1)

[ -n "$tag_name" ] && {
    echo "Current reference has the following tag: ${tag_name}"
    dialog --defaultno --yesno "Are you pushing a tag ?" 20 60 && {
        echo "Checking tag name.."
        # Check if tag follows our semver convention
        # MAJOR.MINOR.PATCH or MAJOR.MINOR.PATCH-SOMETHING.VERSION
        $(echo "$tag_name" | grep -Po "^\d+\.\d+\.\d+(\-[A-z]+\.\d+)?$|^\d+\.\d+\.\d+$" > /dev/null) || {
            echo "Invalid tag name!"
            exit 1
        }
        echo "Tag name is valid, congratulations for the new release!"
    }
}

echo "Running shellcheck..."
#SC2005: Allow us to break line while running command
#SC2015: Allow us to use short circuit
#SC2046: Allow word splitting
#SC2048: Allow word splitting
#SC2086: Allow word splitting
git ls-files '*.sh' | xargs -L 1 shellcheck --exclude=SC2005,SC2015,SC2046,SC2048,SC2086

echo "Running isort.."
# Run isort for each python project
dirname $(git ls-files "$repository_path/*/setup.py") | xargs -I {} pipenv run isort --src-path="{}" ${isort_extra_args} "{}"

# This will only get the python files track by git, not including submodules
python_files=$(git ls-files '*.py')

echo "Running black.."
pipenv run black ${black_extra_args} $python_files

# do not run the rest of the script if running for fixing
[ "$fixing" = true ] && exit 0

# Faster than pylint to check for issues
echo "Running ruff.."
pipenv run ruff $python_files

echo "Running pylint.."
pipenv run pylint $python_files

echo "Running mypy.."
git ls-files '*setup.py' | parallel 'pipenv run mypy $(dirname {}) --cache-dir $(dirname {})'

echo "Running pytest.."
pipenv run pytest -n 10 --cov="$repository_path" --cov-report html

exit 0
