[project]
name = "beacon"
version = "0.1.0"
description = "MDNS service."
requires-python = ">=3.11"
dependencies = [
    "commonwealth==0.1.0",
    "loguru==0.5.3",
    "uvicorn==0.18.0",
    "zeroconf==0.38.4",
]

[tool.uv.sources]
commonwealth = { workspace = true }
